# Generated by Django 5.0.6 on 2024-05-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('owner', models.CharField(max_length=100)),
                ('alt', models.TextField()),
            ],
        ),
    ]
